config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categorywines
  resources :wines
  resources :categories

  root 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categorywines
    has_many :wines, through: :categorywines
end

app/models/categorywine.rb
class Categorywine < ApplicationRecord
  belongs_to :category
  belongs_to :wine
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :categorywines
    has_many :categories, through: :categorywines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authorize_editor!
        unless current_user.editor?
            flash[:alert]= 'You must be an editor to access this section'
            redirect_to_root_path
        end
    end
    def authorize_writer!
        unless current_user.writer?
            flash[:alert]= 'You must be a writer to access this section'
            redirect_to_root_path
        end
    end
    def authorize_reviewer!
        unless current_user.reviewer?
            flash[:alert]= 'You must be a reviewer to access this section'
            redirect_to_root_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/categorywines_controller.rb
class CategorywinesController < ApplicationController
  before_action :set_categorywine, only: %i[ show edit update destroy ]

  # GET /categorywines or /categorywines.json
  def index
    @categorywines = Categorywine.all
  end

  # GET /categorywines/1 or /categorywines/1.json
  def show
  end

  # GET /categorywines/new
  def new
    @categorywine = Categorywine.new
  end

  # GET /categorywines/1/edit
  def edit
  end

  # POST /categorywines or /categorywines.json
  def create
    @categorywine = Categorywine.new(categorywine_params)
    respond_to do |format|
      if @categorywine.save
        format.html { redirect_to categorywine_url(@categorywine), notice: "Categorywine was successfully created." }
        format.json { render :show, status: :created, location: @categorywine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @categorywine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorywines/1 or /categorywines/1.json
  def update
    respond_to do |format|
      if @categorywine.update(categorywine_params)
        format.html { redirect_to categorywine_url(@categorywine), notice: "Categorywine was successfully updated." }
        format.json { render :show, status: :ok, location: @categorywine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categorywine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorywines/1 or /categorywines/1.json
  def destroy
    @categorywine.destroy

    respond_to do |format|
      format.html { redirect_to categorywines_url, notice: "Categorywine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorywine
      @categorywine = Categorywine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categorywine_params
      params.require(:categorywine).permit(:category_id, :wine_id)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_editor!, only: %i[new]
  before_action :authorize_reviewer!, only: %i[show]
  before_action :authenticate_editowriter!, only: %i[_form]
  before_action :set_wine, only: %i[ show edit update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, {category_ids: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorywines_helper.rb
module CategorywinesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categorywines/_form.html.erb
<%= form_with(model: categorywine, local: true) do |form| %>
  <% if categorywine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(categorywine.errors.count, "error") %> prohibited this categorywine from being saved:</h2>

      <ul>
      <% categorywine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :categories %>
    <%= form.collection_check_boxes(:category_id, Category.all, :id, :name) do |b|%>
      <%= b.label class: 'label-checkbox' do%>
      <%= b.check_box + b.text%>
    <%end%>
  <%end%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categorywines/edit.html.erb
<h1>Editing Categorywine</h1>

<%= render 'form', categorywine: @categorywine %>

<%= link_to 'Show', @categorywine %> |
<%= link_to 'Back', categorywines_path %>

app/views/categorywines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorywines</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Wine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categorywines.each do |categorywine| %>
      <tr>
        <td><%= categorywine.wine.name %></td>
        <td><%= categorywine.category.name %></td>
        <td><%= link_to 'Show', categorywine %></td>
        <td><%= link_to 'Edit', edit_categorywine_path(categorywine) %></td>
        <td><%= link_to 'Destroy', categorywine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categorywine', new_categorywine_path %>

app/views/categorywines/new.html.erb
<h1>New Categorywine</h1>

<%= render 'form', categorywine: @categorywine %>

<%= link_to 'Back', categorywines_path %>

app/views/categorywines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @categorywine.category %>
</p>

<p>
  <strong>Wine:</strong>
  <%= @categorywine.wine %>
</p>

<%= link_to 'Edit', edit_categorywine_path(@categorywine) %> |
<%= link_to 'Back', categorywines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vinos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <!--CSS Bootstrap-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Wines', wines_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Categories', categories_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Ensamblaje', categorywines_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  

    <%= yield %>

  <!--JS Bootstrap-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>

</html>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :categories %>
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
      <%= b.label class:"label-checkbox" do %>
        <%= b.check_box + b.text%>
      <%end%>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.categories.map(&:name).join(',') %></td>
        
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>



<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>